### ISSUE TITLE
notification Support ?

### ISSUE THREAD

**Issue by Alii-isk** [linkkader/easy_downloader#1]
hi  thank for the amazing package 
one question:
download notification not showing and found no documentation about that
whats `AndroidManifest.xml `configuration?

**Comment by Alii-isk** [comment]
i see you removed notification in the current version why??

**Comment by linkkader** [comment]
Hi @Alii-isk yes i remove it because i encounter some problem on ios
and be careful this plugin is not yet stable

**Comment by Alii-isk** [comment]
> Hi @Alii-isk yes i remove it because i encounter some problem on ios
> and be careful this plugin is not yet stable 

Thank u,
I am only using it for andoid 
If I revert to the commit before notifications removed ,will it still works on android because I really need it?

**Comment by farooq958** [comment]
notification not working on android 11,12,13

**Comment by linkkader** [comment]
try new version
