### ISSUE TITLE
Notification not working

### ISSUE THREAD

**Issue by noeljayson** [linkkader/easy_downloader#12]
**Description**

**Steps To Reproduce**

**Expected Behavior**

**Screenshots**

**Additional Context**

**Comment by linkkader** [comment]
@noeljayson i publish new version let me know if your problem is solved

**Comment by noeljayson** [comment]
The code taken from github is showing error. Showing initialization error.
There are so many folders cannot recognize which folder to run.

**Comment by linkkader** [comment]
try new version
